/adaptive_clustering:
  ros__parameters:
    cluster_size_max: 500
    cluster_size_min: 5
    generate_bounding_boxes: true
    k_merging_threshold: 0.10000000149011612
    leaf: 1
    print_fps: false
    radius_max: 120.0
    radius_min: 0.4000000059604645
    sensor_model: VLP-16
    z_axis_max: 3.0
    z_axis_min: -0.800000011920929
    z_merging_threshold: 0.0
    car_width: 2.0
    car_length: 4.8768